name: Test R package
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  test:
    name: Test R package
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4'
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
    - name: Check R package (R CMD CHECK)
      uses: r-lib/actions/check-r-package@v2
